INSERT INTO events (id, name, type, created_at, updated_at) VALUES
(415, 'Chiller avec KnTry', 'artists', NOW(), NOW()),
(418, 'Atelier musique avec Cassie', 'artists', NOW(), NOW()),
(419, 'Atelier musique avec ElectriK', 'artists', NOW(), NOW()),
(358, 'Concert avec Cassie', 'concerts', NOW(), NOW()),
(364, 'Concert Blues avec Bluzzi', 'concerts', NOW(), NOW()),
(367, 'Concert Country avec KnTry', 'concerts', NOW(), NOW()),
(370, 'Concert Electro avec ElectriK', 'concerts', NOW(), NOW()),
(392, 'Concert de Rocki', 'concerts', NOW(), NOW()),
(398, 'Concert Jazzi', 'concerts', NOW(), NOW()),
(400, 'Concert Pop avec Poppi', 'concerts', NOW(), NOW()),
(413, 'Séance de répétition avec Bluzzi', 'artists', NOW(), NOW()),
(412, 'Breaktime avec Poppi', 'artists', NOW(), NOW()),
(408, 'Séance d\'autographes avec Rocki', 'artists', NOW(), NOW()),
(407, 'Rencontre avec Jazzi', 'artists', NOW(), NOW());
